services:
  be10app:
    image: jerry8287/be10play
    environment:
      SECRET: "R4h@s1A!"
      SERVERPORT: 8000
      Name: "echorm"
      Address: mysqlData
      Port: 3306   
      Username: "root"
      Password: "jerry123"
    ports:
      - 8001:8000

  